spring:
  application:
    name: cloud.cachecloud-web.local
    import: classpath:spring/spring.xml

server:
  port: 8080
  #ip/域名地址
  domain: http://127.0.0.1:8080
  servlet:
    jsp:
      init-parameters:
        development: true #jsp 热部署

cachecloud:
  primary:
    url: jdbc:mysql://127.0.0.1:3306/cachecloud_open?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&connectTimeout=3000&socketTimeout=10000&serverTimezone=Asia/Shanghai
    user: root
    password: 123456
    initialPoolSize: 1
    maxPoolSize: 3
  redis: #配置cachecloud-web需要的redis，用户存储任务流log
    main:
      host: 127.0.0.1
      port: 6379
      password:
  #区分资源
  web:
    clients: 127.0.0.1
