spring:
  profiles:
    active: local
  main:
    allow-bean-definition-overriding: true
  mvc:
    servlet:
      load-on-startup: 1
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    freemarker:
      expose-request-attributes: true
      request-context-attribute: request
      suffix: .jsp
      settings:
        number_format: computer
    log-resolved-exception: true
    contentnegotiation:
      favor-path-extension: true
    pathmatch:
      use-suffix-pattern: true
      use-registered-suffix-pattern: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
cachecloud:
  jdbc:
    driver: com.mysql.cj.jdbc.Driver
    validationQuery: select 1 from dual
management:
  server:
    port: 8889
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: true
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
    shutdown: #关闭不安全控制endpoints
      enabled: false
    restart:
      enabled: false
    pause:
      enabled: false
    heapdump:
      enabled: false
    refresh:
      enabled: false
    auditevents:
      enabled: false
    jolokia:
      enabled: false
    env:
      post:
        enabled: false